[package]
name = "agb"
version = "0.9.2"
authors = ["Corwin Kuiper <corwin@kuiper.dev>", "Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
description = "Library for Game Boy Advance Development"
license = "MPL-2.0"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
lto = true
debug = true

[features]
default = []
freq18157 = ["agb_sound_converter/freq18157"]
freq32768 = ["agb_sound_converter/freq32768"]
testing = []

[dependencies]
bitflags = "1"
agb_image_converter = { version = "0.7.0", path = "../agb-image-converter" }
agb_sound_converter = { version = "0.2.0", path = "../agb-sound-converter" }
agb_macros = { version = "0.2.0", path = "../agb-macros" }
agb_fixnum = { version = "0.2.1", path = "../agb-fixnum" }
bare-metal = "1"
modular-bitfield = "0.11"
rustc-hash =  { version = "1", default-features = false }

[package.metadata.docs.rs]
default-target = "thumbv6m-none-eabi"
targets = []

[[example]]
name = "mixer_32768"
required-features = ["freq32768"]